# Generated by Django 2.2.4 on 2019-08-20 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190820_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='articel_id',
            new_name='article_id',
        ),
    ]
