# Generated by Django 2.2.4 on 2019-08-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rumour',
            fields=[
                ('rumour_id', models.AutoField(primary_key=True, serialize=False)),
                ('rumour_content', models.TextField()),
                ('rumour_predicted_label', models.IntegerField()),
                ('rumour_prediced_prob', models.FloatField()),
                ('rumour_true_label', models.IntegerField()),
                ('rumour_submit_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
